// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0rsiud4o8SARQ4SCjxAsjgKYRwED3SU',
    appId: '1:86873070835:web:5c0add43cb5d093f242b86',
    messagingSenderId: '86873070835',
    projectId: 'encipharm-c33ac',
    authDomain: 'encipharm-c33ac.firebaseapp.com',
    storageBucket: 'encipharm-c33ac.firebasestorage.app',
    measurementId: 'G-09WLRPW76S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTC4pTGfbPF83ru2yawp5cVuePGFfkOM',
    appId: '1:86873070835:android:2123bba4d7a6b595242b86',
    messagingSenderId: '86873070835',
    projectId: 'encipharm-c33ac',
    storageBucket: 'encipharm-c33ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOsIg2zh4Bv6nzG4ZQGa9XjnDj4bl1M7g',
    appId: '1:86873070835:ios:482b48c008ad8ea9242b86',
    messagingSenderId: '86873070835',
    projectId: 'encipharm-c33ac',
    storageBucket: 'encipharm-c33ac.firebasestorage.app',
    iosClientId: '86873070835-mi7u5sjjan39s084rnjjp7u0do8bmvf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVendedor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOsIg2zh4Bv6nzG4ZQGa9XjnDj4bl1M7g',
    appId: '1:86873070835:ios:482b48c008ad8ea9242b86',
    messagingSenderId: '86873070835',
    projectId: 'encipharm-c33ac',
    storageBucket: 'encipharm-c33ac.firebasestorage.app',
    iosClientId: '86873070835-mi7u5sjjan39s084rnjjp7u0do8bmvf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVendedor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB0rsiud4o8SARQ4SCjxAsjgKYRwED3SU',
    appId: '1:86873070835:web:90a96b0dcf0f2332242b86',
    messagingSenderId: '86873070835',
    projectId: 'encipharm-c33ac',
    authDomain: 'encipharm-c33ac.firebaseapp.com',
    storageBucket: 'encipharm-c33ac.firebasestorage.app',
    measurementId: 'G-HYJJSX7PKF',
  );
}
